name: couldai_user_app
description: "A powerful Web AI Assistant."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_markdown: ^0.7.1
  google_fonts: ^6.1.0
  provider: ^6.1.1
  uuid: ^4.3.3
  intl: ^0.19.0
  image_picker: ^1.0.7
  file_picker: ^8.0.0
  url_launcher: ^6.2.5
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
